name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1 #Setup Node
        with:
          node-version: '16'
      - name: Run Tests
        run: |
          npm install
          npm run test